# Generated by Django 3.0.8 on 2020-07-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Email'),
        ),
    ]
