# Generated by Django 3.0.8 on 2020-07-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200708_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
